spring:
  datasource:
    url: jdbc:h2:mem:turbinedev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    basic:
      enabled: false
  flyway:
    enabled: false
logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE
