
CREATE TABLE AUTH_USER_GROUP (
                                 AUTH_USER_GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                                 USERNAME VARCHAR(128) NOT NULL,
                                 AUTH_GROUP VARCHAR(128) NOT NULL,
                                 CONSTRAINT USER_AUTH_USER_GROUP_FK FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME),
                                 UNIQUE (USERNAME, AUTH_GROUP)
);


INSERT INTO USER (USERNAME, PASSWORD) VALUES ('fpmoles', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('jdoe', '$2a$11$3NO32OV1TGjap3xMpAEjmuiizitWuaSwUYz42aMtlxRliwJ8zm4Sm');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('fpmoles', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('fpmoles', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('jdoe', 'USER');